### ISSUE TITLE
Can not open files in WSL2 sessions

### ISSUE THREAD

**Issue by zobbo** [shirou/vscode-dired#21]
When connected to a WSL2 issue I can browse directories but trying to open a file gives me 

`[UriError]: If a URI does not contain an authority component, then the path cannot begin with two slash characters ("//")`

I need this extension so badly, I'm half tempted to try and learn how to code visual studio extensions :). Many thanks for what you've done so far!

VSC 1.67.2 running on Windows 11, accessing WSL2

**Comment by jrun** [comment]
I don't know much about vscode extensions and I don't have time to work up a PR. That said, I was able to hack `fileitem.js` to fix this issue for me. It seems `vscode.Uri.file` should be used instead of `Uri.parse` when working with a path to a file. YMMV.

```javascript
 get uri() {
        const p = path.join(this._dirname, this._filename);
        if (this._isDirectory) {
            return vscode.Uri.parse(`${provider_1.default.scheme}://${p}`);
        }
        else if (this._isFile) {
            return vscode.Uri.file(p);
        }
        return undefined;
    }
```
