### ISSUE TITLE
Possible to open the highlighted file

### ISSUE THREAD

**Issue by carlosedp** [shirou/vscode-dired#3]
How can I open the file highlighted? I hit "enter" and it's not opening.

I'm on Windows 7.

**Comment by sandric** [comment]
+1

**Comment by carlosedp** [comment]
When I try to open it, I see two notifications on my VSCode:

> Could not get stat of /etc/passwd
> Could not get stat of /etc/group

This only happens on Windows. On Mac it works correctly.

**Comment by shirou** [comment]
These two files are used to resolve user name from user id, at [here](https://github.com/shirou/vscode-dired/blob/master/src/idResolver.ts#L22). And windows doesn't have these files.

I don't have time to continue developing this extension.but PR is always welcome.

**Comment by shirou** [comment]
closed by #6
