### ISSUE TITLE
Cannot invoke dired

### ISSUE THREAD

**Issue by uchuugaka** [shirou/vscode-dired#4]
First, thank you for creating this extension.
I have looked many times for a dired port for VS Code or Atom!

After installing vscode-dired, 
When I do
C-x f

dired doesn't appear.
I also do not see it in the command palette.

Do I also need to first install any particular Emacs key bindings extension?

よろしくお願いします

**Comment by shirou** [comment]
Actually, I am not actively develop this extension. But it can work for me.
How about open a some file and then, type `C-x f` ?

**Comment by shirou** [comment]
closed by #6
